In [1]:
import numpy as np

In [2]:
#Scenario 1

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [3]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [4]:
#Scenario 2

a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [5]:
a3 + a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

## BroadCasting

### The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations.

## Rules for BroadCasting

In [7]:
# If x=m and y=n, operation will take place

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [9]:
## If x=1 and y=n then also operation will take place(Same Dimension)

a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)

print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
a5 + a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])